version: '2'
services:
    consumerservice-app:
        image: consumerservice
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://consumerservice-mysql:3306/consumerservice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    consumerservice-mysql:
        extends:
            file: mysql.yml
            service: consumerservice-mysql
